### ISSUE TITLE
[FHIR — ResearchStudy] Add a program & title for ABC-DS & BRI-DSR

### ISSUE THREAD

**Issue by jthib077** [include-dcc/inc-portal-model#1]
Environment: FHIR QA

**Goal**: Add a program for ABC-DS & BRI-DSR. Add a study name for ABC-DS

1) Program:

- There is missing the` program` field for both ABC-DS and BRI-DSR under the ResearchStudy resource. 
- FHIR attribute for `program`:
<img width="539" alt="image" src="https://user-images.githubusercontent.com/89399893/188947360-082c7039-df50-4f21-8432-bea6f8b636aa.png">

2) Study Name:

- The study title for ABC-DS should be "Alzheimer's Biomarker Consortium - Down Syndrome"
- FHIR attribute for `study name`:
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/89399893/188948086-32a0d5c2-4e50-4300-b648-e6c876ec90b0.png">

**Comment by jthib077** [comment]
The title of ABC-DS was fixed and the program was added for both ABC-DS and BRI-DSR. However, the program value is supposed to be `INCLUDE` as per the study file in Sage and not `INCLUDE/KF`

**Comment by torstees** [comment]
2nd times the charm? Should be corrected now.
