### ISSUE TITLE
Missing `Data Type` for some BRI-DSR files

### ISSUE THREAD

**Issue by lopierra** [include-dcc/inc-portal-model#11]
`Data Type` is missing for annoFuse_filter.tsv files in BRI-DSR. Per Meen's [Khor manifest](https://docs.google.com/spreadsheets/d/1fHaTM06UfecSkzLVBA9IsEIkKIDnQnbBpJucxmGSywU/edit?pli=1#gid=407949218), the Data Type should be `Annotated Gene Fusion`

**Comment by jthib077** [comment]
I think there may be missing the type attribute for these specific files. Perhaps the Annotated Gene Fusion wasn't a part of the enumeration in the codesystem? 

**Codesystem:** https://includedcc.org/fhir/code-systems/data_types"](https://includedcc.org/fhir/code-systems/data_types

**Issue Reference:** https://include-api-fhir-service-qa.includedcc.org/DocumentReference?identifier=BRI-DSR.09729910-2420-4ce3-990a-ad8f202b0139.annoFuse_filter.tsv

![image](https://user-images.githubusercontent.com/89399893/192811155-83f924fe-aa80-4b41-87a7-5b52648cc2cb.png)

**Comment by torstees** [comment]
Added new code to the CodeSystem and pushed to QA. https://include-api-fhir-service-qa.includedcc.org/CodeSystem?url=https://includedcc.org/fhir/code-systems/data_types

Added the reference in the Harmony file and the data type now appears correctly on my local dev machine. Should be fine on reload
