### ISSUE TITLE
Missing MONDO codes + duplicated Condition Source Texts

### ISSUE THREAD

**Issue by lopierra** [include-dcc/inc-portal-model#13]
Here are a few examples where MONDO codes aren't showing up:

- The MONDO code for Vitamin D deficiency is not showing up (should be MONDO:0100471) (also the highlight is not in the right place - there is a dash where the vitamin D code should be)

![image](https://user-images.githubusercontent.com/34149564/192675427-b17560b9-123a-44b1-85bd-27e8cba0d2c2.png)

- In the `Condition Source Text` for ABCDS 22884, Anxiety/OCD is listed 3 times but Syncope is missing. Similar duplication of Anxiety in the `Diagnosis (MONDO)` column (Syncope should not have a MONDO code). HP looks fine.

![image](https://user-images.githubusercontent.com/34149564/192811236-af66456e-044a-4170-b633-54e439522124.png)

- Similar for ABCDS 10046 - MONDO code for Mosaic Trisomy 21 not showing up, Anxiety is repeated several times in `Condition Source Text` and `Diagnosis (MONDO)` columns

![image](https://user-images.githubusercontent.com/34149564/192810842-51da92c2-01de-4dac-b099-c99f327404b2.png)

**Comment by jthib077** [comment]
The repeated anxiety code will be a FHIR issue. Is the Syncope supposed to have a MONDO code? If so, I believe it is missing from FHIR: https://include-api-fhir-service-qa.includedcc.org/Condition?subject=613059

For the Mosaic Trisomy 21, vitamin d deficiency,  this is on the portal side, I think maybe we don't have the latest MONDO version up and it is not picking up certain terms. We will double check.

**Comment by torstees** [comment]
For the Anxiety/OCD, I'm only seeing one condition for this person: 

https://include-api-fhir-service-qa.includedcc.org/Condition?code=MONDO:0005618&subject=Patient/613059

If it is in FHIR, it's related would be coming from multiple mondo codes but I don't see any others matching OCD in the data so I can't easily find them using FHIR.

**Comment by jthib077** [comment]
I think it is because you are filtering for MONDO:0005618 but there is another MONDO code for anxiety coming into play here. You'll see 2 Anxiety/OCD in the `text` : https://include-api-fhir-service-qa.includedcc.org/Condition?subject=612704

**Comment by lopierra** [comment]
@jthib077 Syncope does not have a MONDO code - I edited my text to reflect that. And we did add numerous codes to MONDO - the latest version was released in August 2022, so it's possible that you didn't have the new terms yet.

Also, there are multiple codes  related to Anxiety in the ontology, but I only selected one per condition per patient in the all_cohorts_condition.csv file

@torstees is that ABCDS 22884? If so, they have multiple conditions that are in the [all_cohorts_condition.csv](https://www.synapse.org/#!Synapse:syn35304566) file.

**Comment by torstees** [comment]
@lopierra I only see a single row with the word anxiety for each 22884 and 10046 (ABC-DS). If you can give me a bit more info, I may be able to understand what the problem is a bit quicker

**Comment by lopierra** [comment]
Correct, in all_conditions_cohort.csv there is only 1 Anxiety row for each 22884 and 10046, with MONDO:0005618. 

If you look at the last 2 screenshots above, in the `Diagnosis (MONDO)` column, Anxiety appears once (correctly) as `Anxiety disorder (MONDO:0005618)` and twice (incorrectly) as `Anxiety (MONDO:0011918)`

**Comment by torstees** [comment]
@lopierra OK. This looks like some old conditions from an older version of the data weren't removed prior to the load (if you look at the 3 conditions in JPs query, 2 of them have 9/1 dates and one of them is from 9/9). That explains why I couldn't find those additional Anxiety codes in the data. This is technically fixed and will be fine if I drop all of ABC-DS prior to reload.

**Comment by lopierra** [comment]
The duplication of Anxiety has been fixed - thanks! Now just waiting on the updated MONDO codes.

**Comment by lopierra** [comment]
MONDO codes fixed, thank you! Note that Monarch Initiative links for updated MONDO codes (e.g. Vitamin D deficiency) aren't working - links need to be switched to OLS (#20)
