### ISSUE TITLE
MONDO codes for specific DS subtypes not showing up

### ISSUE THREAD

**Issue by lopierra** [include-dcc/inc-portal-model#14]
[Split from #10 ]

The MONDO code for the specific DS subtype (e.g. complete trisomy 21, mosaic trisomy 21, etc.) is not showing up in the Diagnosis (MONDO) column (see screenshots below; I can't speak to KF since I didn't handle that data)

**Solution, per @jthib077**

> For point https://github.com/include-dcc/inc-portal-model/issues/2, it is a portal/MONDO issue. We fetch all the MONDO codes available in a obo file format that the MONDO team releases. We searched in our current version for the MONDO codes missing, complete trisomy, mosaic, vitamin d deficiency, etc. and they were not appearing.
> We usually download this file: http://purl.obolibrary.org/obo/mondo.obo but it does not seem to be loading so this issue will need to be fixed post ABC-DS demo.

![image](https://user-images.githubusercontent.com/34149564/192674221-e2b9b91e-e676-4fcd-815d-f11e580fb23f.png)

![image](https://user-images.githubusercontent.com/34149564/192674244-fd86229a-58b4-44f4-9679-a0b21c837367.png)

**Comment by torstees** [comment]
@lopierra I believe these are correct in FHIR, though, I've asked JP to double check in case there is a subtle issue with the .text portion of the coding. However, for BRI-DSR, there doesn't appear to be any subtypes which would cause the example you've shown to not have any subtypes (since there weren't any for my code to pick up on).

**Comment by lopierra** [comment]
Bri_DSR was the example for #10 (sorry for the confusion). The screenshots here are both for DS-Connect. The DS subtype appears correctly in the Condition Source Text column, but the MONDO code is just a dash.

**Comment by lopierra** [comment]
Codes are showing up now, but need to be updated for HTP (#19) and links need to be switched to OLS (#20)
