### ISSUE TITLE
`Race` has "Other" and "other"

### ISSUE THREAD

**Issue by lopierra** [include-dcc/inc-portal-model#15]
There are two "Other" values in the `Race` facet - "other" is lowercase in PCGC and uppercase in BRI-DSR.

![image](https://user-images.githubusercontent.com/34149564/193070856-b3230b5c-eb22-4cd2-a932-969d56c5524d.png)

**Comment by torstees** [comment]
This looks more like an issue with Meen's data. From what I'm seeing, everything else uses capitol letters for start: White, Black, etc (and HTP also uses Other). The text, however, is typically expected to be the value as it was originally provided as opposed to a mapped value.

**Comment by jthib077** [comment]
It does seem like this is the mapped value though. Wondering if the enumeration can be changed to "O"ther instead of "o"ther on Meen's side. 

![image](https://user-images.githubusercontent.com/89399893/193085185-df61a80a-7e70-4683-b759-8c0b7d58f21a.png)

**Comment by torstees** [comment]
Interesting. So, are the HTP data showing up as "Other" or "other"?

Technically, this display is defined by HL7 and shouldn't be changed. This looks like I probably need to add that code instead of the UKN which I'm using, which is fine.

**Comment by torstees** [comment]
This is totally on me. I was using the wrong code system for "other". This will be fixed when I load the data next
