### ISSUE TITLE
BRI-DSR `Age at Sample Collection` is in years, not days

### ISSUE THREAD

**Issue by lopierra** [include-dcc/inc-portal-model#16]
The Age facet for sample collection is in days, but the BRI-DSR ages are in years (see screenshot below from their [publication](https://pubmed.ncbi.nlm.nih.gov/35020411/))

![image](https://user-images.githubusercontent.com/34149564/193074361-dae0166c-eff8-4440-b91f-e2610a6c303a.png)

![image](https://user-images.githubusercontent.com/34149564/193074485-a70afa27-2fd7-48ad-93d0-e4e7061c573b.png)

**Comment by torstees** [comment]
OK. No one gave me a DD for the specimen data so I just assumed age. Will fix this for the push later today.

**Comment by lopierra** [comment]
@torstees I don't think we have a DD for specimen data yet. 

Only HTP and BRI-DSR have ages currently. HTP is in days, BRI-DSR is in years. Might be easiest to ask @liberaliscomputing to convert the BRI-DSR ages to days?

**Comment by torstees** [comment]
This should be corrected in upcoming push to QA.
