### ISSUE TITLE
Size does not appear for BRI-DSR

### ISSUE THREAD

**Issue by jthib077** [include-dcc/inc-portal-model#18]
Goal: Adjust the FHIR attribute used to capture the size. It seems like it differs from the other studies. 

https://include-api-fhir-service-qa.includedcc.org/DocumentReference?_tag=DS360-CHD

https://include-api-fhir-service-qa.includedcc.org/DocumentReference?_tag=BRI-DSR

![image](https://user-images.githubusercontent.com/89399893/193341927-b203b9fc-19db-4ff9-8f8f-d960e1bc6dc0.png)

![image](https://user-images.githubusercontent.com/89399893/193341998-446657d6-826a-4de6-aa07-2542cbd3a49d.png)

**Comment by torstees** [comment]
Fixed in commit e957f63..f9ccbd1
