### ISSUE TITLE
Family Type - Coding within both Family group and Family ID Observation

### ISSUE THREAD

**Issue by torstees** [include-dcc/inc-portal-model#3]
We are currently representing family membership in a handful of ways: 
* Group with references to patients as members
* Observation with Family ID as the valueString
* Observations denoting the relationship between members of the same family (currently, there are no relationships other than "FAMMEMB" due to the limitations of the data that we currently have. 

For the Group and Family ID observation, we can add the Family Type coding from the local code system (or external code system if we find codes to map to that suffice)

Question:                  Do we want groups with a single patient for those "Proband Only" family types

For Future Reference: I suggest we ultimate profile Group so that it can serve both purposes of the group membership and family ID observation. This would force the answer to the question above to be "Yes".

**Comment by RobertJCarroll** [comment]
I think it makes sense to have a family group for every participant. It would make navigating easier I think- you don't have to check to see "is there a family group" when you look across studies.

The profile suggestion is sensible as well. We don't need a profile to enable those two purposes, though, right? The identifier of the group would be the family ID and it would still handle group membership. Unless I'm missing something; it seems like a helpful communication aid.

**Comment by torstees** [comment]
Example of an Family ID Observation with the Family Type 
`   {
      "code": {
        "coding": [
          {
            "code": "Family ID",
            "display": "Unique identifier for family to which Participant belongs",
            "system": "https://nih-ncpi.github.io/ncpi-fhir-ig/CodeSystem/data-dictionary/BRI-DSR/participant",
            "version": "v1"
          },
          {
            "code": "Proband-only",
            "display": "Proband-only",
            "system": "https://nih-ncpi.github.io/ncpi-fhir-ig/CodeSystem/data-dictionary/BRI-DSR/participant/family_type",
            "version": "v1"
          }
        ]
      },
      "identifier": [
        {
          "system": "https://includedcc.org/abc-ds/fhir/observation",
          "use": "official",
          "value": "ABC-DS.participant.Family ID.10119"
        }
      ],
      "meta": {
        "tag": [
          {
            "code": "ABC-DS",
            "system": "https://includedcc.org/abc-ds/fhir/researchstudy"
          }
        ]
      },
      "resourceType": "Observation",
      "status": "final",
      "subject": {
        "identifier": {
          "system": "https://includedcc.org/abc-ds/fhir/group",
          "value": "ABC-DS.10119"
        }
      },
      "valueString": "10119"
    },`

**Comment by torstees** [comment]
The advantage of a profile is just that it makes it easier to find all of that type of group. We are using groups to represent other types of membership, such as consent group, study membership, etc.

**Comment by lopierra** [comment]
We will eventually have Family Relationship values (Parent, Sibling, etc.) - I just didn't include any this time because we (the Data Modeling Group) are still trying to figure out how to model families and what ontology to use. 

cc @include-dcc/data-model-wg

**Comment by torstees** [comment]
@lopierra Understood. We are definitely aware that is on the horizon and will work that into the next iteration where there is consensus on how we are handling that.

**Comment by torstees** [comment]
It seems the consensus is for us to move forward with a profiled Group resource that has: Family ID, Type and membership at some point in the future. My current approach does all of this except for the non-existent profile, and is still producing the Family ID observations which I think the portal is currently using.
